"""add ingest_jobs

Revision ID: 38cc69732ee9
Revises: b1e9938e8b98
Create Date: 2026-04-30 18:02:40.559551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cc69732ee9'
down_revision: Union[str, None] = 'b1e9938e8b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_trip_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_jobs_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_owner_id'))

    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
