"""add trip.published_slug

Revision ID: 5b693a15c159
Revises: 8e2c011bf237
Create Date: 2026-05-15 00:53:08.239428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b693a15c159'
down_revision: Union[str, None] = '8e2c011bf237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_slug', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_trips_published_slug'), ['published_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_published_slug'))
        batch_op.drop_column('published_slug')

    # ### end Alembic commands ###
