"""add stop.promo

Revision ID: 8e2c011bf237
Revises: b6a78381897d
Create Date: 2026-05-14 21:58:02.420212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2c011bf237'
down_revision: Union[str, None] = 'b6a78381897d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo', sa.JSON(), nullable=True))

    # ### end Alembic commands ###

    # KG-2 demo seed: attach a promo to the first "Vienna Airport (VIE)" stop
    # so the orange promo banner is visible on existing demo DBs (the seeder
    # only runs on fresh installs and is idempotent by trip name).
    op.execute(
        """
        UPDATE stops
           SET promo = '{"label": "Vienna eSIM (demo)", "price": "€19", "url": "https://example.com/esim"}'
         WHERE promo IS NULL
           AND id = (SELECT MIN(id) FROM stops WHERE name LIKE 'Vienna Airport%')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_column('promo')

    # ### end Alembic commands ###
