"""init schema

Revision ID: ad110b1e6a9a
Revises: 
Create Date: 2026-04-30 17:37:58.942919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad110b1e6a9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('season', sa.String(length=40), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('pace', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('hotel_lat', sa.Float(), nullable=True),
    sa.Column('hotel_lng', sa.Float(), nullable=True),
    sa.Column('hotel_address', sa.String(length=300), nullable=False),
    sa.Column('journal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_owner_id'), ['owner_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_trip_id'), ['trip_id'], unique=False)

    op.create_table('companion_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companion_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companion_docs_trip_id'), ['trip_id'], unique=False)

    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('date_label', sa.String(length=40), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_days_trip_id'), ['trip_id'], unique=False)

    op.create_table('route_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('day_n', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('map_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_assets_trip_id'), ['trip_id'], unique=False)

    op.create_table('street_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('price_band', sa.String(length=20), nullable=False),
    sa.Column('price_huf', sa.String(length=60), nullable=False),
    sa.Column('locality_score', sa.Float(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('hours', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('street_food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_street_food_trip_id'), ['trip_id'], unique=False)

    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('time_label', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('hours', sa.String(length=255), nullable=False),
    sa.Column('tickets', sa.String(length=255), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('transit', sa.Text(), nullable=False),
    sa.Column('washroom', sa.Text(), nullable=False),
    sa.Column('food', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_day_id'), ['day_id'], unique=False)

    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_ins_stop_id'), ['stop_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_stop_id'), ['stop_id'], unique=False)

    op.create_table('voice_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_notes_stop_id'), ['stop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_notes_stop_id'))

    op.drop_table('voice_notes')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_stop_id'))

    op.drop_table('photos')
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_ins_stop_id'))

    op.drop_table('check_ins')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_day_id'))

    op.drop_table('stops')
    with op.batch_alter_table('street_food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_street_food_trip_id'))

    op.drop_table('street_food')
    with op.batch_alter_table('route_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_assets_trip_id'))

    op.drop_table('route_assets')
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_days_trip_id'))

    op.drop_table('days')
    with op.batch_alter_table('companion_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companion_docs_trip_id'))

    op.drop_table('companion_docs')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_trip_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_owner_id'))

    op.drop_table('trips')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
