"""add photo_url to street_food

Revision ID: b6a78381897d
Revises: 38cc69732ee9
Create Date: 2026-05-01 17:25:38.076114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a78381897d'
down_revision: Union[str, None] = '38cc69732ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street_food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street_food', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
