"""Budapest 5-day demo trip — ported from the original tour_companion.html TRIP+STATE."""
from datetime import date

DEMO_USER = {
    "email": "demo@tourcompanion.app",
    "password": "demo1234",
    "display_name": "Demo Traveler",
}

TRIP = {
    "name": "Budapest 5 Days · Spring 2026",
    "destination": "Budapest, Hungary",
    "start_date": date(2026, 5, 22),
    "end_date": date(2026, 5, 26),
    "season": "Late spring (18–25 °C)",
    "style": "Mixed: history + thermal + food",
    "pace": "Moderate",
    "source_url": "https://youtube.com/playlist?list=PLtV2zB28YXqiyU5iLzzXJNNWn_VRhDrIl",
    "hotel_name": "Astoria",
    "hotel_lat": 47.4929,
    "hotel_lng": 19.0586,
    "hotel_address": "1088 Budapest, Kossuth Lajos u. 19–21",
    "journal": (
        "Friday: arrived stretched but pumped. Bors GasztroBár hit the spot. "
        "Saturday: Parliament tour was a highlight. Sunday morning now and we're heading up to Buda Castle."
    ),
}

BOOKINGS = [
    {"label": "Hungarian Parliament tour — Sat 09:00 English", "url": "https://www.jegymester.hu/parlament", "done": True},
    {"label": "Hospital in the Rock — Sun ~14:00", "url": "https://www.sziklakorhaz.eu/", "done": True},
    {"label": "Legenda sunset cruise — Fri 20:30", "url": "https://www.legenda.hu/", "done": True},
    {"label": "Farewell dinner Tue — Borkonyha or Halászbástya", "url": "", "done": False},
]

COMPANION_DOCS = [
    {"name": "🍲 Food guide", "file_path": "/static/Budapest_5_Day/food.md"},
    {"name": "🗣 Phrasebook", "file_path": "/static/Budapest_5_Day/phrasebook.md"},
    {"name": "🚻 Washroom finder", "file_path": "/static/Budapest_5_Day/washrooms.md"},
    {"name": "📋 Full itinerary", "file_path": "/static/Budapest_5_Day/Budapest_5_Day_Itinerary.md"},
]

ROUTES = [
    {"day_n": 1, "label": "Day 1 · Pest icons + cruise",
     "pdf_path": "/static/Budapest_5_Day/routes/Day_1_Friday_May22_route.pdf",
     "map_url": "https://www.google.com/maps/dir/Astoria,+Budapest/Bors+Gastro+Bar,+Budapest/Shoes+on+the+Danube+Bank,+Budapest/St.+Stephen's+Basilica,+Budapest/Vigad%C3%B3+t%C3%A9r,+Budapest/?travelmode=walking"},
    {"day_n": 2, "label": "Day 2 · Parliament → Heroes → Bath",
     "pdf_path": "/static/Budapest_5_Day/routes/Day_2_Saturday_May23_route.pdf",
     "map_url": "https://www.google.com/maps/dir/Astoria,+Budapest/Hungarian+Parliament+Building,+Budapest/Oktogon,+Budapest/Heroes'+Square,+Budapest/Sz%C3%A9chenyi+Thermal+Bath,+Budapest/?travelmode=transit"},
    {"day_n": 3, "label": "Day 3 · Buda Castle + Gellért",
     "pdf_path": "/static/Budapest_5_Day/routes/Day_3_Sunday_May24_route.pdf",
     "map_url": "https://www.google.com/maps/dir/Astoria,+Budapest/Buda+Castle/Fisherman's+Bastion/Hospital+in+the+Rock/Citadel/Szimpla+Kert/?travelmode=transit"},
    {"day_n": 4, "label": "Day 4 · Market + Margaret Island",
     "pdf_path": "/static/Budapest_5_Day/routes/Day_4_Monday_May25_route.pdf",
     "map_url": "https://www.google.com/maps/dir/Astoria,+Budapest/Great+Market+Hall/Hungarian+National+Museum/Vigad%C3%B3+t%C3%A9r/Margaret+Island/?travelmode=transit"},
    {"day_n": 5, "label": "Day 5 · Szentendre walking loop",
     "pdf_path": "/static/Budapest_5_Day/routes/Day_5_Tuesday_May26_route.pdf",
     "map_url": "https://www.google.com/maps/dir/Szentendre,+2000+Hungary/Marzipan+Museum/F%C5%91+t%C3%A9r/Blagovestenska+Church/Templom+t%C3%A9r/Belgrade+cathedral/Margit+Kov%C3%A1cs+Ceramic+Museum/?travelmode=walking"},
]


DAYS = [
    {"n": 1, "date_label": "Fri 22 May", "theme": "Arrival → Pest Icons → Sunset Cruise", "mode": "Walking", "stops": [
        {"time_label": "13:30", "name": "Astoria (hotel check-in)", "lat": 47.4929, "lng": 19.0586,
         "address": "1088 Budapest", "note": "Drop bags, freshen up"},
        {"time_label": "14:30", "name": "Bors GasztroBár (lunch)", "lat": 47.4969, "lng": 19.0606,
         "address": "Kazinczy u. 10, 1075 Budapest", "hours": "Daily 11:30–22:00",
         "tickets": "Soup + baguette ~1,800 HUF",
         "food": ["Beef pho 1,800 HUF", "Lamb baguette 2,200 HUF"]},
        {"time_label": "16:00", "name": "Shoes on the Danube Bank", "lat": 47.5039, "lng": 19.0448,
         "address": "Id. Antall József rkp., 1054 Budapest", "hours": "24/7", "tickets": "Free",
         "intro": "Sixty pairs of cast-iron shoes — memorial to Jews shot at the river's edge in 1944–45.",
         "highlights": ["Read the bronze plaque at the south end", "Continue south to Chain Bridge"],
         "transit": "M2 → Kossuth Lajos tér, walk 5 min south",
         "washroom": "Marriott lobby (Apáczai Csere János u. 4) — order an espresso",
         "food": ["Spinoza Café (Dob u. 15) — chicken paprikash"]},
        {"time_label": "17:00", "name": "St. Stephen's Basilica + dome", "lat": 47.5006, "lng": 19.0539,
         "address": "Szent István tér 1, 1051 Budapest",
         "hours": "Mon–Sat 9:00–17:45, Sun 13:00–17:45",
         "tickets": "Combined ticket ~3,200 HUF",
         "intro": "Hungary's largest church — domed at exactly 96 m to match the Parliament.",
         "highlights": ["Drop a 200 HUF coin to light the Holy Right relic", "Climb 364 stairs (or take elevator + 42)"],
         "transit": "Walk 8 min south down Október 6 utca",
         "washroom": "Free WC inside basilica with dome ticket",
         "food": ["First Strudel House of Pest", "Stand 25 Bistro Michelin Bib"]},
        {"time_label": "20:00", "name": "Vigadó tér · Legenda cruise pier", "lat": 47.4955, "lng": 19.0494,
         "address": "Vigadó tér, 1051 Budapest", "hours": "Cruise departs 20:30",
         "tickets": "Sunset cocktail cruise 5,500 HUF",
         "intro": "70-minute Danube night cruise with the entire skyline gilded by night lights.",
         "highlights": ["Get a riverside seat on the upper deck", "Drink included in the ticket"],
         "transit": "Walk 10 min west on Deák Ferenc utca",
         "washroom": "On board, deck level",
         "food": ["Pesti Disznó (Nagymező u. 19)"]},
    ]},
    {"n": 2, "date_label": "Sat 23 May",
     "theme": "Parliament → Andrássy → Heroes Sq → Széchenyi Bath", "mode": "Transit + walking", "stops": [
        {"time_label": "09:00", "name": "Hungarian Parliament tour", "lat": 47.5072, "lng": 19.0457,
         "address": "Kossuth Lajos tér 1-3, 1055 Budapest", "hours": "Daily 8:00–18:00",
         "tickets": "10,000 HUF (booked)",
         "intro": "Third-largest parliament in the world. 691 rooms, 88 statues.",
         "highlights": ["Arrive 30 min early for the changing of the guard"],
         "transit": "M2 (red) → Kossuth Lajos tér",
         "washroom": "Free WC inside Visitor Centre with tour ticket",
         "food": ["Buja Disznók (Hold u. 13) — langos breakfast"]},
        {"time_label": "10:30", "name": "Walk Andrássy Avenue → Oktogon", "lat": 47.5054, "lng": 19.0637,
         "address": "Andrássy út, 1067 Budapest",
         "intro": "UNESCO-listed grand boulevard.",
         "highlights": ["Pass the Opera House for façade photos", "Try Művész Kávéház for opera-day cake set"],
         "transit": "Walk 2 km north-east", "washroom": "Művész Kávéház customer WC",
         "food": ["Klassz (Andrássy út 41)"]},
        {"time_label": "12:30", "name": "Lunch at Bock Bisztró", "lat": 47.5079, "lng": 19.0635,
         "address": "Erzsébet krt. 43-49, 1073 Budapest", "hours": "11:30–23:00",
         "tickets": "Mains ~5,500 HUF",
         "food": ["Mangalica chops", "Grandma's chicken paprikash with nokedli"]},
        {"time_label": "14:00", "name": "Heroes' Square + City Park", "lat": 47.5149, "lng": 19.0779,
         "address": "Hősök tere, 1146 Budapest", "hours": "24/7", "tickets": "Free",
         "intro": "The grandest square in Budapest — Millennium Monument with seven Magyar chieftains on horseback.",
         "highlights": ["Vajdahunyad Castle a 5-min walk into City Park", "Boating lake rentals in spring"],
         "transit": "M1 (yellow line) from Oktogon → Hősök tere",
         "washroom": "Free WC in Museum of Fine Arts (with ticket)",
         "food": ["Bagolyvár (Állatkerti krt. 2)"]},
        {"time_label": "15:00", "name": "House of Music Hungary", "lat": 47.5132, "lng": 19.0836,
         "address": "Olof Palme stny. 3, 1146 Budapest", "hours": "Tue–Sun 10:00–18:00",
         "tickets": "~3,500 HUF",
         "intro": "2022 Sou Fujimoto-designed concert hall + sound museum.",
         "highlights": ["Walk under the perforated golden canopy", "Sound dome on the lower floor"]},
        {"time_label": "16:30", "name": "Széchenyi Thermal Bath", "lat": 47.5187, "lng": 19.0824,
         "address": "Állatkerti krt. 9-11, 1146 Budapest",
         "hours": "Daily 7:00–19:00 (last entry 18:00)",
         "tickets": "10,500 HUF weekday with cabin",
         "intro": "Yellow neo-Baroque bath complex — 18 pools, three huge outdoor pools.",
         "highlights": ["Go around 17:00 to bathe through golden hour", "Outdoor whirlpool"],
         "transit": "5-min walk from House of Music", "washroom": "Inside the bath complex",
         "food": ["Pántlika Bisztró in the park"]},
    ]},
    {"n": 3, "date_label": "Sun 24 May",
     "theme": "Buda Castle → Bastion → Hospital in the Rock → Gellért Hill",
     "mode": "Transit + walking", "stops": [
        {"time_label": "09:30", "name": "Buda Castle (Royal Palace)", "lat": 47.4962, "lng": 19.0395,
         "address": "Szent György tér 2, 1014 Budapest", "hours": "Grounds 24/7; museums 10:00–18:00",
         "tickets": "Free grounds; museums ~3,800 HUF",
         "intro": "Castle Hill cobbled streets and palaces — the President's residence.",
         "highlights": ["Bus 16 from Deák tér — free with travelcard", "Walk Tóth Árpád sétány"],
         "transit": "Bus 16 from Deák Ferenc tér (5 min)",
         "washroom": "Free WCs in palace courtyard between Wing C and D",
         "food": ["Walzer Café (Táncsics Mihály u. 12)"]},
        {"time_label": "10:30", "name": "Matthias Church + Fisherman's Bastion", "lat": 47.5020, "lng": 19.0344,
         "address": "Szentháromság tér, 1014 Budapest",
         "hours": "Bastion 24/7; upper terraces 9:00–19:00",
         "tickets": "Bastion upper 1,500 HUF; church 2,500 HUF",
         "intro": "Seven white neo-Romanesque turrets over the Danube + the diamond-tile-roof Matthias Church.",
         "highlights": ["Free trick: enter before 9:00 or after 19:00", "Best photo angle: lower turret"],
         "transit": "Walk 8 min north on Tárnok utca",
         "washroom": "Paid WC 300 HUF at Szentháromság tér",
         "food": ["Café Pierrot (Fortuna u. 14)"]},
        {"time_label": "14:00", "name": "Hospital in the Rock", "lat": 47.5008, "lng": 19.0314,
         "address": "Lovas út 4/c, 1012 Budapest",
         "hours": "Daily 10:00–19:00, hourly tours",
         "tickets": "7,000 HUF (booked, English tour)",
         "intro": "Beneath Castle Hill lies a 10-km cave network. WWII secret hospital, Cold War nuclear bunker.",
         "highlights": ["Constant 14 °C — bring a light jacket", "Photography NOT allowed"],
         "transit": "5-min walk west on Lovas út", "washroom": "Free WC inside lobby",
         "food": ["Anjuna Café (Lovas út 41)"]},
        {"time_label": "17:30", "name": "Gellért Hill + Citadella sunset", "lat": 47.4869, "lng": 19.0460,
         "address": "Citadella sétány, 1118 Budapest", "hours": "24/7", "tickets": "Free",
         "intro": "14-m bronze Liberty Statue on the summit.",
         "highlights": ["25-min hike up switchback paths", "Cave Church on the way ~700 HUF", "Stay for sunset"],
         "transit": "Walk down to Clark Ádám tér + bus 8E/110",
         "washroom": "No public WC on summit — go before climbing",
         "food": ["Hadik Kávéház (Bartók Béla út 36)"]},
        {"time_label": "21:00", "name": "Szimpla Kert (ruin bar)", "lat": 47.4975, "lng": 19.0628,
         "address": "Kazinczy u. 14, 1075 Budapest", "hours": "Daily 12:00–04:00",
         "tickets": "Free entry; drinks ~1,800 HUF",
         "intro": "The original ruin pub — a maze of mismatched furniture, a Trabant car turned booth.",
         "highlights": ["Famously decorated WCs", "Karaván food court next door"],
         "transit": "Tram 47/49 across Liberty Bridge",
         "food": ["Karaván Street Food (Kazinczy u. 18)"]},
    ]},
    {"n": 4, "date_label": "Mon 25 May",
     "theme": "Central Market → Palace District → Tram 2 → Margaret Island",
     "mode": "Walking + Tram 2", "stops": [
        {"time_label": "09:30", "name": "Great Market Hall", "lat": 47.4870, "lng": 19.0584,
         "address": "Vámház körút 1-3, 1093 Budapest",
         "hours": "Mon 06:00–17:00; Tue–Fri 06:00–18:00; Sat 06:00–15:00; Sun closed",
         "tickets": "Free entry",
         "intro": "Neo-Gothic 1897 market — three floors of paprika, salami, Tokaji.",
         "highlights": ["Lángos at upstairs corner — 2,000 HUF", "Buy paprika tins + Tokaji Aszú"],
         "transit": "Tram 47/49 → Fővám tér",
         "washroom": "Paid 250 HUF in basement",
         "food": ["Lángos Sarok upstairs"]},
        {"time_label": "11:00", "name": "Palace District (Józsefváros) walk", "lat": 47.4904, "lng": 19.0651,
         "address": "Múzeum krt., 1088 Budapest",
         "intro": "Your hotel's neighborhood — Hungarian National Museum + 19th-century palaces.",
         "highlights": ["Hungarian National Museum classical façade (closed Mon)"],
         "transit": "10-min walk south from Astoria",
         "washroom": "FSZEK library or any nearby café"},
        {"time_label": "14:30", "name": "Tram 2 — scenic riverside", "lat": 47.4955, "lng": 19.0494,
         "address": "Vigadó tér Tram 2 stop, 1051 Budapest",
         "hours": "Trams every 5–10 min", "tickets": "Included in 96-hour travelcard",
         "intro": "National Geographic-rated 'world's most scenic tramline'.",
         "highlights": ["Best window seats: right side facing the river"]},
        {"time_label": "18:30", "name": "Margaret Island musical fountain", "lat": 47.5290, "lng": 19.0478,
         "address": "Margitsziget, 1138 Budapest", "hours": "Choreographed shows every hour",
         "tickets": "Free",
         "intro": "2.5 km car-free island — locals' weekend escape.",
         "highlights": ["Rent a Bringóhintó pedal cart 4,000 HUF/h", "Mini zoo with deer and peacocks"],
         "transit": "Tram 4/6 stops mid-bridge",
         "washroom": "Free public WCs along the central path",
         "food": ["Holdudvar — restaurant + open-air bar"]},
    ]},
    {"n": 5, "date_label": "Tue 26 May",
     "theme": "Szentendre Day Trip + Farewell Dinner",
     "mode": "HÉV + walking", "stops": [
        {"time_label": "09:40", "name": "Szentendre HÉV station", "lat": 47.6608, "lng": 19.0755,
         "address": "Szentendre, 2000 Hungary",
         "tickets": "HÉV supplement 750 HUF each way",
         "intro": "End of HÉV H5 line from Batthyány tér.",
         "transit": "HÉV H5 from Batthyány tér (40 min)",
         "washroom": "Paid 200 HUF inside station"},
        {"time_label": "10:00", "name": "Marzipan Museum & Café", "lat": 47.6664, "lng": 19.0765,
         "address": "Dumtsa Jenő u. 14, 2000 Szentendre", "hours": "Daily 10:00–18:00",
         "tickets": "1,200 HUF",
         "intro": "Quirky museum of life-size marzipan sculptures.",
         "highlights": ["Quick 20-min visit", "Café out front sells marzipan ice cream"]},
        {"time_label": "10:30", "name": "Fő tér (Main Square)", "lat": 47.6677, "lng": 19.0757,
         "address": "Fő tér, 2000 Szentendre", "tickets": "Free",
         "intro": "Pastel baroque facades, the 1763 Plague Cross, Serbian Orthodox church.",
         "highlights": ["Photograph the cobbled square from the eastern corner", "Coffee at Palmetta Café"]},
        {"time_label": "11:30", "name": "Templom-domb (Church Hill)", "lat": 47.6681, "lng": 19.0754,
         "address": "Templom tér, 2000 Szentendre", "hours": "24/7", "tickets": "Free",
         "intro": "Hilltop panorama over the old town and the Danube.",
         "highlights": ["Best wide-angle view of the town", "5-min climb up cobbled steps"]},
        {"time_label": "13:00", "name": "Lánchíd Söröző (lunch on Fő tér)", "lat": 47.6677, "lng": 19.0758,
         "address": "Fő tér, 2000 Szentendre", "hours": "Daily 11:00–22:00",
         "tickets": "Mains ~3,500 HUF",
         "intro": "Riverbank tavern serving honest Hungarian classics.",
         "food": ["Halászlé (river-fish stew) 3,200 HUF", "Schnitzel + chips 3,800 HUF"]},
        {"time_label": "14:30", "name": "Margit Kovács Ceramic Museum", "lat": 47.6677, "lng": 19.0771,
         "address": "Vastagh György u. 1, 2000 Szentendre", "hours": "Tue–Sun 10:00–18:00",
         "tickets": "1,800 HUF",
         "intro": "Hungary's most famous 20th-century ceramicist.",
         "highlights": ["~75 min visit", "Most pieces are kissable-small"]},
        {"time_label": "20:00", "name": "Farewell dinner at Borkonyha", "lat": 47.5009, "lng": 19.0537,
         "address": "Sas u. 3, 1051 Budapest", "hours": "Mon–Sat 12:00–24:00; closed Sun",
         "tickets": "Tasting menu ~32,000 HUF (booked)",
         "intro": "1-Michelin-star wine restaurant near the Basilica.",
         "highlights": ["Order the duck liver with poppy seed", "Tokaji Aszú flight pairing"]},
    ]},
]


# Pre-existing in-tour state (from STATE in original demo)
# Day 1 + 2 fully done; Day 3 has stop 0 done
CHECK_INS = {1: [0, 1, 2, 3, 4], 2: [0, 1, 2, 3, 4, 5], 3: [0]}

VOICE_NOTES = {
    (1, 3): "Crossed the Chain Bridge at sunset. The Parliament across the river — unbelievable.",
    (2, 0): "Took the Parliament tour at 9. Crown room is small but the guard ceremony was moving.",
    (2, 5): "Széchenyi after sunset. The outdoor pools steamed in the cool air.",
}

# Photo paths reference the existing /static asset bundle (mounted from upload_dir or external)
PHOTOS = {
    (1, 2): ["/static/Budapest_5_Day/images/05_new_york_cafe.jpg"],
    (1, 3): ["/static/Budapest_5_Day/images/02_basilica.jpg"],
    (1, 4): ["/static/Budapest_5_Day/images/06_chain_bridge.jpg"],
    (2, 0): ["/static/Budapest_5_Day/images/01_parliament.jpg"],
    (2, 3): ["/static/Budapest_5_Day/images/14_heroes_square.jpg"],
    (2, 5): ["/static/Budapest_5_Day/images/16_szechenyi_bath.jpg"],
    (3, 0): ["/static/Budapest_5_Day/images/07_buda_castle.jpg"],
}


STREET_FOOD = [
    {"slug": "florian-langos", "name": "Flórián tér underpass lángos", "category": "langos",
     "lat": 47.5400, "lng": 19.0411, "address": "Flórián tér underpass, 1033 Óbuda",
     "price_band": "local", "price_huf": "1,200–1,800", "locality_score": 0.95,
     "why": "Cash-only stall in metro underpass. Hungarian-only menu. Construction-worker lunch crowd.",
     "hours": "Mon–Sat 06:00–14:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Budapest%2C_B%C3%A9k%C3%A1smegyer%2C_piac%2C_sajtos-tejf%C3%B6l%C3%B6s_l%C3%A1ngos.jpg"},
    {"slug": "karavan", "name": "Street Food Karaván", "category": "food_court",
     "lat": 47.4972, "lng": 19.0626, "address": "Kazinczy u. 18, 1075 Budapest",
     "price_band": "mid", "price_huf": "1,800–2,500", "locality_score": 0.72,
     "why": "Card-friendly food-truck court in Jewish Quarter. Touristy at night but locals come for late lunch. Lángos here ~500–800 HUF.",
     "hours": "Daily 12:00–02:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Budapest%2C_Street_Food_Karav%C3%A1n.jpg"},
    {"slug": "frici-papa", "name": "Frici Papa Kifőzdéje", "category": "kifozde",
     "lat": 47.5042, "lng": 19.0653, "address": "Király u. 55, 1077 Budapest",
     "price_band": "local", "price_huf": "2,000–3,500 (set menu)", "locality_score": 0.92,
     "why": "Old-school worker's canteen (kifőzde). Hungarian-only menu, cafeteria trays, daily 'Napi Menü'. Office lunch crowd.",
     "hours": "Mon–Fri 11:30–22:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Frici_Papa_Kif%C5%91zd%C3%A9je_at_55_Kir%C3%A1ly_Street_Budapest%2C_Erzs%C3%A9betv%C3%A1ros%2C_Hungary_-_panoramio.jpg"},
    {"slug": "langos-land", "name": "Lángos Land (Fény tér market)", "category": "langos",
     "lat": 47.5106, "lng": 19.0259, "address": "Fény u. 12, 1024 Budapest (Mammut II side)",
     "price_band": "local", "price_huf": "1,200–1,800", "locality_score": 0.88,
     "why": "Inside Buda's Fény tér market hall. Locals eat standing up next to the stall. Cash + card.",
     "hours": "Mon–Sat 06:00–18:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/8/83/F%C3%A9ny_utcai_piac_010.jpg"},
    {"slug": "bors", "name": "Bors GasztroBár", "category": "soup_baguette",
     "lat": 47.4969, "lng": 19.0606, "address": "Kazinczy u. 10, 1075 Budapest",
     "price_band": "mid", "price_huf": "1,800–2,500", "locality_score": 0.78,
     "why": "Tiny 4-seat soup + baguette spot. Long queue of locals at lunch. Daily-changing soups, lamb baguette is the move.",
     "hours": "Mon–Sat 11:30–20:30",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/7/72/Budapest%2C_Street_Food_Karav%C3%A1n%2C_2.jpg"},
    {"slug": "belvarosi-disznotoros", "name": "Belvárosi Disznótoros", "category": "butcher",
     "lat": 47.4968, "lng": 19.0567, "address": "Király u. 1/D, 1075 Budapest",
     "price_band": "local", "price_huf": "2,500–3,500", "locality_score": 0.83,
     "why": "Stand-up butcher counter. Point at the sausage/blood-pudding/krumpli. Nagy Tamás-style traditional, no tourist menu.",
     "hours": "Mon–Sat 09:00–20:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Christmas_market_2015_Erzs%C3%A9bet_Square._Meat_products._-_Budapest.JPG"},
    {"slug": "bangla", "name": "Bangla Bufé Premium", "category": "international",
     "lat": 47.4986, "lng": 19.0648, "address": "Akácfa u. 40, 1073 Budapest",
     "price_band": "local", "price_huf": "1,500–1,900 (full meal)", "locality_score": 0.86,
     "why": "Bangladeshi curry buffet, point-and-pick. Non-tourist crowd. Vegetarian options under 1,500 HUF.",
     "hours": "Mon–Sun 11:00–22:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Bengali_dishes%2C_Gagan_Assam_Bengal_Restaurant_%2801%29.jpg"},
    {"slug": "kato-neni", "name": "Kató Néni Finomságai (kürtős)", "category": "kurtos",
     "lat": 47.5012, "lng": 19.0553, "address": "Október 6. u. 22, 1051 Budapest",
     "price_band": "mid", "price_huf": "1,800–2,500", "locality_score": 0.65,
     "why": "Honest kürtőskalács stall away from Váci tourist drag. Baked on the spot — always insist on warm/fresh.",
     "hours": "Daily 10:00–20:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/7/77/K%C3%BCrt%C5%91skal%C3%A1cs_Budapest_2008.jpg"},
    {"slug": "molnars-kurtos", "name": "Molnár's Kürtőskalács", "category": "kurtos",
     "lat": 47.4928, "lng": 19.0533, "address": "Váci u. 31, 1052 Budapest",
     "price_band": "tourist", "price_huf": "2,200–2,800", "locality_score": 0.45,
     "why": "Historic 1922 spot but on tourist-trap Váci utca. Quality is real, price ~30% above neighborhood spots.",
     "hours": "Daily 10:00–22:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/K%C3%BCrt%C5%91skal%C3%A1cs_in_Budapest.jpg"},
    {"slug": "strudel-house", "name": "First Strudel House of Pest", "category": "strudel",
     "lat": 47.5008, "lng": 19.0556, "address": "Október 6. u. 22, 1051 Budapest",
     "price_band": "local", "price_huf": "1,200–1,800", "locality_score": 0.74,
     "why": "Mom-and-pop strudel bakery. Apricot, poppy seed, túró (curd cheese). Mostly walk-in regulars.",
     "hours": "Daily 10:00–19:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/3/35/Neoclassical_corner_house_by_Fid%C3%A9l_Kasselik_in_1812._-_Budapest_District_V.%2C_Arany_Street_12_and_October_6th_Street_22.jpg"},
    {"slug": "market-langos", "name": "Lángos Sarok (Great Market Hall upstairs)", "category": "langos",
     "lat": 47.4870, "lng": 19.0584, "address": "Vámház krt. 1-3 (1st floor), 1093 Budapest",
     "price_band": "tourist", "price_huf": "2,000–4,000", "locality_score": 0.35,
     "why": "Tourist-priced. Avoid the 'gourmet bolognese' versions at 4,000 HUF. Plain cheese + sour cream is the only fair bet.",
     "hours": "Mon 06:00–17:00; Tue–Fri 06:00–18:00; Sat 06:00–15:00; Sun closed",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Eating_Langosh_and_Spicy_Sausage.jpg"},
    {"slug": "retro-langos", "name": "Retro Lángos Budapest", "category": "langos",
     "lat": 47.5031, "lng": 19.0563, "address": "Bajcsy-Zsilinszky út 22, 1051 Budapest",
     "price_band": "tourist", "price_huf": "1,500–4,000", "locality_score": 0.40,
     "why": "Heavily marketed to tourists. Loaded versions hit 4,000 HUF — same dough as a 1,200 HUF stall in Óbuda.",
     "hours": "Daily 11:00–22:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Budapest%2C_Retro_L%C3%A1ngos_B%C3%BCf%C3%A9.jpg"},
    {"slug": "pesti-disznó", "name": "Pesti Disznó", "category": "sausage_pub",
     "lat": 47.5034, "lng": 19.0608, "address": "Nagymező u. 19, 1065 Budapest",
     "price_band": "mid", "price_huf": "3,500–5,500", "locality_score": 0.70,
     "why": "Mangalica pork specialist. Pre-theatre crowd from the Operetta. Card-friendly.",
     "hours": "Mon–Sat 12:00–24:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/0/01/2018-06-26_Sausages%2C_salami_and_meat_on_sale_at_Grand_Market_Hall%2C_Budapest%2C_Hungary.jpg"},
    {"slug": "karavan-gyros", "name": "Karaván gyros truck", "category": "gyros",
     "lat": 47.4974, "lng": 19.0628, "address": "Kazinczy u. 18 (inside Karaván)",
     "price_band": "mid", "price_huf": "1,800–2,500", "locality_score": 0.68,
     "why": "Late-night gyros from a converted truck. Open till 02:00 — popular post-Szimpla.",
     "hours": "Daily 12:00–02:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Budapest%2C_Street_Food_Karav%C3%A1n%2C_3.jpg"},
    {"slug": "pantlika", "name": "Pántlika Bisztró", "category": "park_bistro",
     "lat": 47.5169, "lng": 19.0820, "address": "Hermina út, Városliget, 1146 Budapest",
     "price_band": "mid", "price_huf": "2,500–3,500", "locality_score": 0.70,
     "why": "Retro pavilion in City Park near Széchenyi. Goulash + fried fish at honest prices despite the tourist neighborhood.",
     "hours": "Daily 11:00–23:00",
     "photo_url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/P%C3%A1ntlika_Bistro_%281964%29._-_Budapest_City_Park.jpg"},
]
