"""Vienna + Budapest 10-day trip — synced from ChicTrip planner 2026/05/18-2026/05/27
(chictrip.com.tw/explore) and merged with local Budapest/ and vienna/ notes.
"""
from datetime import date

from . import budapest as bp


TRIP = {
    "name": "Vienna + Budapest · 10 Days · Spring 2026",
    "destination": "Vienna, Austria + Budapest, Hungary",
    "start_date": date(2026, 5, 18),
    "end_date": date(2026, 5, 27),
    "season": "Late spring (15–24 °C)",
    "style": "Imperial cities · castles · Danube",
    "pace": "Packed",
    "source_url": "https://www.chictrip.com.tw/explore",
    "hotel_name": "arte Hotel Wien Stadthalle (Days 1–4) · Extremly Central Balcony, Budapest (Days 5–10)",
    "hotel_lat": 48.1985,
    "hotel_lng": 16.3357,
    "hotel_address": "Mariahilfer Str., 1150 Wien (Vienna leg)",
    "journal": "",
}

BOOKINGS = [
    {"label": "Vancouver YVR → Vienna VIE flight — Sun May 17", "url": "", "done": False},
    {"label": "Dinner Mon 5/18 18:30 · Gasthaus Rebhuhn (#BfxkOe)", "url": "https://rebhuhn.at/en/home/", "done": True},
    {"label": "Dinner Tue 5/19 18:45 · Melker Stiftskeller", "url": "https://www.melkerstiftskeller.at/en/menu", "done": True},
    {"label": "Austrian Parliament visit — Tue 5/19 16:45 (free, registered)", "url": "https://www.parlament.gv.at/", "done": True},
    {"label": "Schönbrunn Palace tour — Tue 5/19 (NT$2,179, Grand Tour)", "url": "https://www.schoenbrunn.at/en/tickets-and-prices/all-tickets-tours", "done": False},
    {"label": "Kunsthistorisches Museum ticket — Wed 5/20 (NT$812)", "url": "https://www.khm.at/en/visit", "done": False},
    {"label": "Vienna Fiaker carriage tour — Day 1 (NT$1,200)", "url": "https://www.fiaker.at/", "done": False},
    {"label": "Wachau OBB combo (train + DDSG boat + Melk Abbey) — Thu 5/21", "url": "https://ddsg-blue-danube.at/cruises-wachau/?lang=en", "done": False},
    {"label": "Vienna → Budapest train (ÖBB Railjet) — Fri 5/22 morning", "url": "https://www.oebb.at/", "done": False},
    {"label": "Hungarian Parliament tour — Fri 5/22 morning English", "url": "https://www.jegymester.hu/parlament", "done": False},
    {"label": "Budapest 15-day transit pass · 5,950 HUF (vs 5,500 for 72hr — buy 15)", "url": "https://bkk.hu/en/", "done": False},
    {"label": "Hungarian State Opera — Sat 5/23 18:00", "url": "https://www.opera.hu/", "done": False},
    {"label": "Danube night cruise · Hajóznijó €18 / Viator €15–16", "url": "https://hajoznijo.hu/budapest-boat-cruises/budapest-city-highlights-cruise/", "done": False},
    {"label": "Dinner Tue 5/26 18:00 · Retek Bistro Budapest", "url": "https://retekbisztro.hu/en/retek-eng/", "done": True},
    {"label": "Europe eSIM (NT$69)", "url": "https://www.chictrip.com.tw/", "done": False},
    {"label": "Budapest BUD departure — Wed 5/27 03:37", "url": "", "done": False},
]

COMPANION_DOCS = [
    {"name": "🇦🇹 ChicTrip source plan", "file_path": "https://www.chictrip.com.tw/explore"},
    {"name": "🍲 Budapest goulash guide", "file_path": "https://maps.app.goo.gl/LaRXbPb8rZPc9ant7"},
    {"name": "🥨 Vienna food spots", "file_path": "https://maps.app.goo.gl/R12ihax3omCbdTf69"},
    {"name": "🚐 Vienna parking guide", "file_path": "https://www.wien.gv.at/en/transportation/parking-fees"},
    {"name": "🚆 Budapest metro / HÉV map", "file_path": "https://elte.esn.hu/maps"},
    {"name": "🍷 Wachau Valley guide", "file_path": "https://kimiyo.tw/wachau-valley-town/"},
    {"name": "🏊 Budapest baths official", "file_path": "https://www.spasbudapest.com"},
    {"name": "🛍 Budapest shopping malls", "file_path": "https://monkeywalker.com/shopping-mall-in-budapest"},
    {"name": "🚻 Washroom finder", "file_path": ""},  # opens modal
    {"name": "🗣 Phrasebook (DE/HU)", "file_path": ""},  # opens modal
]

ROUTES = [
    {"day_n": 1, "label": "Day 1 · Vienna icons (Stephansdom + Hofburg)", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Vienna+Airport/arte+Hotel+Wien+Stadthalle/Fenster+Cafe+Vienna/Ankeruhr/Mozarthaus+Vienna/Stephansdom/Pestsaule/Peterskirche/Cafe+Demel/Austrian+National+Library/Augustinerkirche/Schweizertor+Hofburg/Heldenplatz/Hofburg+Wien/Mozart+Monument+Burggarten/Gasthaus+Rebhuhn/?travelmode=transit"},
    {"day_n": 2, "label": "Day 2 · Schönbrunn + Naschmarkt + Opera + Parliament", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/arte+Hotel+Wien+Stadthalle/Sch%C3%B6nbrunn+Palace/XO+Grill+1050+Wien/Naschmarkt/Wien+Museum/Karlskirche/Vienna+State+Opera/Austrian+Parliament/Melker+Stiftskeller/?travelmode=transit"},
    {"day_n": 3, "label": "Day 3 · Kunsthistorisches + Hundertwasser + Franzensburg", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/arte+Hotel+Wien+Stadthalle/Kunsthistorisches+Museum+Vienna/Justizpalast+Wien/Hundertwasserhaus/KunstHausWien/Palais+Kinsky/Franzensburg+Laxenburg/Skopik+Lohn+Wien/?travelmode=transit"},
    {"day_n": 4, "label": "Day 4 · Wachau Valley loop", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Klosterneuburg+Monastery/Krems+an+der+Donau/D%C3%BCrnstein+Parkplatz+P3/Aggstein+Castle/Melk+Abbey/St.+P%C3%B6lten/?travelmode=driving"},
    {"day_n": 5, "label": "Day 5 · Budapest Parliament + Basilica + Market → Chain Bridge", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Extremly+Central+Balcony+Budapest/McDonald's+Nyugati+Budapest/My+Green+Cup+Budapest/Hungarian+Parliament/Shoes+on+the+Danube/St.+Stephen's+Basilica+Budapest/Belv%C3%A1rosi+Diszn%C3%B3toros/Great+Market+Hall+Budapest/Chain+Bridge+Budapest/L%C3%A1nch%C3%ADd+S%C3%B6r%C3%B6z%C5%91/?travelmode=walking"},
    {"day_n": 6, "label": "Day 6 · Library → Synagogue → Heroes → Opera", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Ervin+Szab%C3%B3+Library/Doh%C3%A1ny+Street+Synagogue/New+York+Caf%C3%A9/Heroes+Square+Budapest/Budapest+Zoo/Hungarian+State+Opera/?travelmode=transit"},
    {"day_n": 7, "label": "Day 7 · Buda Castle + Gellért + Szimpla", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Fisherman's+Bastion/Matthias+Church+Budapest/Labyrinth+Buda+Castle/Hungarian+National+Gallery/Buda+Castle/Gell%C3%A9rt+Hill/Palatinus+Strand+Baths/Szimpla+Kert/?travelmode=transit"},
    {"day_n": 8, "label": "Day 8 · Danube Bend (Esztergom → Visegrád → Szentendre)", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Esztergom+Basilica/Visegr%C3%A1d+Castle+Citadel/Renaissance+Restaurant+Visegr%C3%A1d/Szentendre+F%C5%91+t%C3%A9r/?travelmode=driving"},
    {"day_n": 9, "label": "Day 9 · Free day · Retek dinner", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir//Retek+Bisztr%C3%B3+Budapest/?travelmode=transit"},
    {"day_n": 10, "label": "Day 10 · Departure → Liszt Ferenc Airport", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Extremly+Central+Balcony+Budapest/Liszt+Ferenc+Airport+Terminal+2/?travelmode=transit"},
]


DAYS = [
    {"n": 1, "date_label": "Mon 18 May",
     "theme": "Vienna arrival → Stephansdom + Hofburg loop", "mode": "Walking", "stops": [
        {"time_label": "09:00", "name": "Vienna Airport (VIE)", "lat": 48.1102, "lng": 16.5697,
         "address": "1300 Schwechat, Austria", "note": "Pass through · CAT/S7 train to city ~30 min"},
        {"time_label": "10:00", "name": "arte Hotel Wien Stadthalle (check-in)", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Drop bags · 20 min stay"},
        {"time_label": "10:49", "name": "Fenster Café", "lat": 48.2117, "lng": 16.3735,
         "address": "Griechengasse 10, 1010 Wien", "note": "Stay 1 hr · brunch"},
        {"time_label": "11:54", "name": "Ankeruhr (Anker Clock 安可鐘)", "lat": 48.2110, "lng": 16.3741,
         "address": "Hoher Markt 10–11, 1010 Wien",
         "note": "Stay 1 hr · Art-Nouveau musical clock built 1914. 12 historical figures parade with music daily at noon. Connects two former Anker insurance buildings.",
         "highlights": ["Be in place by 11:55 for the noon parade"]},
        {"time_label": "13:00", "name": "Mozarthaus Vienna (莫扎特之家)", "lat": 48.2087, "lng": 16.3727,
         "address": "Domgasse 5, 1010 Wien", "note": "Stay 1 hr · Mozart lived here 1784–87"},
        {"time_label": "14:04", "name": "St. Stephen's Cathedral (Stephansdom)", "lat": 48.2084, "lng": 16.3725,
         "address": "Stephansplatz 3, 1010 Wien", "note": "Stay 1 hr · climb south tower (343 steps)"},
        {"time_label": "15:09", "name": "Plague Column (Pestsäule)", "lat": 48.2088, "lng": 16.3700,
         "address": "Graben, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "16:11", "name": "Peterskirche (St Peter's)", "lat": 48.2096, "lng": 16.3697,
         "address": "Petersplatz, 1010 Wien", "note": "Stay 1 hr · free organ recitals 15:00"},
        {"time_label": "17:15", "name": "Café Demel", "lat": 48.2087, "lng": 16.3667,
         "address": "Kohlmarkt 14, 1010 Wien",
         "note": "Stay 1 hr · imperial Sachertorte, Kaiserschmarrn, Apfelstrudel with cream",
         "food": ["Sachertorte", "Kaiserschmarrn (small portion w/ plum jam)", "Apfelstrudel"]},
        {"time_label": "18:20", "name": "Austrian National Library (Prunksaal)", "lat": 48.2068, "lng": 16.3661,
         "address": "Josefsplatz 1, 1010 Wien", "note": "Stay 1 hr · note closing 18:00 — reschedule earlier if needed"},
        {"time_label": "19:23", "name": "Augustinerkirche", "lat": 48.2058, "lng": 16.3669,
         "address": "Augustinerstraße 3, 1010 Wien", "note": "Stay 1 hr · Habsburg hearts crypt"},
        {"time_label": "20:29", "name": "Schweizertor (Swiss Gate 瑞士人大門)", "lat": 48.2069, "lng": 16.3653,
         "address": "Hofburg, 1010 Wien", "note": "Stay 1 hr · Renaissance gate into Hofburg's oldest courtyard"},
        {"time_label": "21:33", "name": "Heldenplatz", "lat": 48.2065, "lng": 16.3635,
         "address": "Heldenplatz, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "22:36", "name": "Hofburg Palace", "lat": 48.2069, "lng": 16.3650,
         "address": "Michaelerkuppel, 1010 Wien", "note": "Stay 1 hr · Fiaker carriage deal NT$1,200 · Imperial Treasury free"},
        {"time_label": "23:42", "name": "Mozart Monument", "lat": 48.2052, "lng": 16.3637,
         "address": "Burggarten, 1010 Wien", "note": "Stay 30 min"},
        {"time_label": "00:24 +1", "name": "Gasthaus Rebhuhn (dinner)", "lat": 48.2185, "lng": 16.3614,
         "address": "Berggasse 24, 1090 Wien",
         "note": "Stay 1 hr · 18:30 reservation #BfxkOe — Wiener Schnitzel (veal/pork), Wiener sausage · +43 1 319 5058 · reschedule with reception if window slips",
         "food": ["Original Wiener Schnitzel", "Wiener sausage"]},
    ]},

    {"n": 2, "date_label": "Tue 19 May",
     "theme": "Schönbrunn → Naschmarkt → Karlskirche → Opera + Parliament",
     "mode": "Transit + walking", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · breakfast"},
        {"time_label": "09:35", "name": "Schönbrunn Palace (美泉宮)", "lat": 48.1845, "lng": 16.3122,
         "address": "Schönbrunner Schloßstraße 47, 1130 Wien",
         "note": "Stay 3 hr · tour deal NT$2,179 (Grand Tour 40 rooms 50–60 min) · arrive 10–15 min early · audio-guide counter left of glass door (bring own headphones) · avoid carrying backpacks",
         "highlights": ["Grand Tour 38€ inc. guide", "State Apartments 28€ (Vienna Pass)", "Maria Theresia live English tour 39€"]},
        {"time_label": "13:07", "name": "XO Grill 1050", "lat": 48.1899, "lng": 16.3526,
         "address": "Wiedner Hauptstraße, 1050 Wien", "note": "Stay 1 hr · lunch · grill spot near Naschmarkt"},
        {"time_label": "14:15", "name": "Naschmarkt", "lat": 48.1986, "lng": 16.3631,
         "address": "Naschmarkt, 1060 Wien",
         "note": "Stay 1 hr · open-air market · washroom at U4 metro exit",
         "washroom": "Free at Naschmarkt U4 station exit"},
        {"time_label": "15:16", "name": "Georg am Naschmarkt", "lat": 48.1986, "lng": 16.3631,
         "address": "Naschmarkt 33, 1060 Wien",
         "note": "Stay 10 min · Zelten Austrian flatbread (poppy-seed)"},
        {"time_label": "15:30", "name": "Nordsee", "lat": 48.2089, "lng": 16.3712,
         "address": "Kärntner Straße 25, 1010 Wien", "note": "Stay 1 hr · seafood chain"},
        {"time_label": "16:32", "name": "Vienna Secession", "lat": 48.2007, "lng": 16.3658,
         "address": "Friedrichstraße 12, 1010 Wien", "note": "Stay 1 hr · Klimt Beethoven Frieze"},
        {"time_label": "17:40", "name": "Wien Museum (維也納博物館)", "lat": 48.1996, "lng": 16.3712,
         "address": "Karlsplatz 8, 1040 Wien",
         "note": "Stay 1 hr · 1M+ artefacts incl. city scale model · free Wi-Fi · QR audio guide EN only · photos allowed"},
        {"time_label": "18:43", "name": "Karlskirche (卡爾教堂)", "lat": 48.1985, "lng": 16.3722,
         "address": "Karlsplatz, 1040 Wien", "note": "Stay 1 hr · panoramic dome elevator"},
        {"time_label": "19:54", "name": "Alt Wien Kaffee", "lat": 48.2080, "lng": 16.3760,
         "address": "Bäckerstraße 9, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "20:56", "name": "Vollpension", "lat": 48.1968, "lng": 16.3720,
         "address": "Schleifmühlgasse 16, 1040 Wien", "note": "Stay 1 hr · grandmas' cake café"},
        {"time_label": "22:08", "name": "Vienna State Opera", "lat": 48.2025, "lng": 16.3691,
         "address": "Opernring 2, 1010 Wien", "note": "Stay 1 hr · standing-room tickets €4–€10 same-day"},
        {"time_label": "23:18", "name": "Austrian Parliament", "lat": 48.2080, "lng": 16.3585,
         "address": "Dr.-Karl-Renner-Ring 3, 1017 Wien",
         "note": "Stay 1 hr · evening lit façade · free guided tour registered for 16:45 today (bring ID, security screening, no Chinese guide, photo-tour available)",
         "highlights": ["Registered 16:45 visit", "Bring photo ID", "Photos allowed throughout"]},
        {"time_label": "00:25 +1", "name": "Melker Stiftskeller (dinner)", "lat": 48.2117, "lng": 16.3633,
         "address": "Schottengasse 3-3a, 1010 Wien",
         "note": "Stay 1 hr · 18:45 reservation · salt-cured pork knuckle ~1.5 kg (3 ppl), Original Wiener Schnitzel veal, chicken Viennese · cancel link saved",
         "food": ["Salt-cured pork knuckle", "Original Wiener Schnitzel (veal)", "Chicken schnitzel"]},
        {"time_label": "01:50 +1", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · return"},
    ]},

    {"n": 3, "date_label": "Wed 20 May",
     "theme": "Kunsthistorisches + Hundertwasser + Kinsky + Franzensburg",
     "mode": "Transit + driving", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr"},
        {"time_label": "09:17", "name": "Kunsthistorisches Museum (藝術史博物館)", "lat": 48.2038, "lng": 16.3614,
         "address": "Maria-Theresien-Platz, 1010 Wien",
         "note": "Stay 1 hr · ticket NT$812 (€22 online / €24 on-site)"},
        {"time_label": "10:27", "name": "Vienna Palace of Justice (Justizpalast)", "lat": 48.2090, "lng": 16.3568,
         "address": "Schmerlingplatz 11, 1010 Wien",
         "note": "Stay 1 hr · opens 09:30 · security screening · cap 25 / hour in high season · afternoon closes early (~15:30, last entry 14:30) · 5F Justice Café needs purchase to enter",
         "highlights": ["Caryatid atrium", "5F Justice Café panorama (must buy)"]},
        {"time_label": "11:49", "name": "Hundertwasserhaus (百水公寓)", "lat": 48.2076, "lng": 16.3940,
         "address": "Kegelgasse 36–38, 1030 Wien", "note": "Stay 1 hr · photo from outside only"},
        {"time_label": "12:51", "name": "KunstHausWien (百水藝術村)", "lat": 48.2110, "lng": 16.3914,
         "address": "Untere Weißgerberstraße 13, 1030 Wien", "note": "Stay 1 hr · Hundertwasser museum"},
        {"time_label": "14:13", "name": "Palais Kinsky (Daun-Kinsky 金斯基宮)", "lat": 48.2110, "lng": 16.3667,
         "address": "Freyung 4, 1010 Wien",
         "note": "Stay 1 hr · 1713 baroque palace owned by Billa-founder family · only front hallway free · ceiling fresco by Carlo Carlone (trompe-l'œil sky)"},
        {"time_label": "16:44", "name": "Franzensburg (Laxenburg)", "lat": 48.0648, "lng": 16.3589,
         "address": "Schlossplatz 1, 2361 Laxenburg",
         "note": "Stay 1 hr · ~91 min south by car/transit · island castle on park lake"},
        {"time_label": "19:21", "name": "Skopik & Lohn (dinner)", "lat": 48.2167, "lng": 16.3796,
         "address": "Leopoldsgasse 17, 1020 Wien",
         "note": "Stay 1 hr · Leopoldstadt bistro · book ahead",
         "food": ["Tafelspitz", "Wiener Schnitzel"]},
        {"time_label": "20:56", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · return"},
    ]},

    {"n": 4, "date_label": "Thu 21 May",
     "theme": "Wachau Valley · Klosterneuburg → Krems → Dürnstein → Aggstein → Melk",
     "mode": "Driving (rental or guided)", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien",
         "note": "Stay 1 hr · early start, pack lunch · OBB Wachau combo ticket = train + Melk→Krems DDSG boat + Melk Abbey entry, buy in OBB app",
         "highlights": ["OBB app → All Products → Combination Tickets → Wachau-Tickets"]},
        {"time_label": "09:24", "name": "Klosterneuburg Monastery", "lat": 48.3060, "lng": 16.3257,
         "address": "Stiftspl. 1, 3400 Klosterneuburg",
         "note": "Stay 1 hr · Austria's oldest winery + Verdun Altar (Verduner Altar) high artistic value"},
        {"time_label": "11:19", "name": "Krems an der Donau", "lat": 48.4097, "lng": 15.6160,
         "address": "Krems an der Donau", "note": "Stay 1 hr · UNESCO old town · farm-product hub"},
        {"time_label": "12:32", "name": "Dürnstein Parkplatz P3", "lat": 48.3979, "lng": 15.5180,
         "address": "Dürnstein", "note": "Stay 1 hr · prettiest Wachau village · blue church + Richard the Lionheart ruin"},
        {"time_label": "19:55", "name": "Aggstein Castle (阿格斯泰因城堡)", "lat": 48.3093, "lng": 15.4248,
         "address": "Aggstein 5, 3642 Aggsbach",
         "note": "Stay 1 hr · ruined Danube cliff castle · 360° virtual tour online at ruineaggstein.at"},
        {"time_label": "21:57", "name": "Melk Abbey (梅爾克修道院)", "lat": 48.2280, "lng": 15.3340,
         "address": "Abt-Berthold-Dietmayr-Straße 1, 3390 Melk",
         "note": "Stay 1 hr · closes 17:30 — re-time to afternoon or use OBB combo"},
        {"time_label": "23:23", "name": "St. Pölten Tourismus", "lat": 48.2058, "lng": 15.6232,
         "address": "Rathauspl. 1, 3100 St. Pölten", "note": "Stay 1 hr"},
        {"time_label": "01:17 +1", "name": "arte Hotel Wien Stadthalle (late return)", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · consider overnighting in Melk instead"},
    ]},

    {"n": 5, "date_label": "Fri 22 May",
     "theme": "Budapest · Parliament + Basilica + Central Market + Chain Bridge",
     "mode": "Walking", "stops": [
        {"time_label": "08:00", "name": "Extremly Central - Balcony (BP hotel check-in)", "lat": 47.4990, "lng": 19.0570,
         "address": "Budapest",
         "note": "Stay 30 min · drop bags after Vienna→Budapest train · buy 15-day transit pass 5,950 HUF (only 450 more than 72hr pass)"},
        {"time_label": "08:43", "name": "McDonald's Nyugati", "lat": 47.5104, "lng": 19.0571,
         "address": "Teréz krt. 55, 1062 Budapest",
         "note": "Stay 1 hr · breakfast inside the restored Nyugati station hall · 'Nyugati Lounge' light show Fri/Sat 22:00–04:00 if you swing by at night",
         "highlights": ["Goosey Gustav foie gras burger nearby"]},
        {"time_label": "09:50", "name": "My Green Cup", "lat": 47.5050, "lng": 19.0537,
         "address": "Bajcsy-Zsilinszky út, 1054 Budapest", "note": "Stay 1 hr · specialty coffee stop"},
        {"time_label": "11:00", "name": "Hungarian Parliament", "lat": 47.5072, "lng": 19.0457,
         "address": "Kossuth Lajos tér 1–3, 1055 Budapest",
         "note": "Stay 1 hr · book English tour ahead via jegymester.hu · free WC at visitor centre outside",
         "washroom": "Free at the visitor service centre outside the building"},
        {"time_label": "12:09", "name": "Shoes on the Danube Bank", "lat": 47.5039, "lng": 19.0454,
         "address": "Id. Antall József rkp., 1054 Budapest",
         "note": "Stay 1 hr · WWII memorial · 60 cast-iron pairs"},
        {"time_label": "13:26", "name": "St. Stephen's Basilica", "lat": 47.5009, "lng": 19.0537,
         "address": "Szent István tér 1, 1051 Budapest",
         "note": "Stay 1 hr · climb dome 364 steps · drop 200 HUF coin for Holy Right relic",
         "food": ["Bestia goulash (Szent István tér 9–11) — spiciest in city ~3,000 HUF", "Stephen Confectionery Dobos torta (Október 6 u. 17)"]},
        {"time_label": "14:40", "name": "Belvárosi Disznótoros - Károlyi utca", "lat": 47.4912, "lng": 19.0581,
         "address": "Károlyi u., 1053 Budapest",
         "note": "Stay 1 hr · point-at-the-sausage butcher counter · try red Sült Kolbász + blood-sausage Hurka",
         "food": ["Sült Kolbász (red sausage)", "Hurka (blood sausage)"]},
        {"time_label": "15:49", "name": "Great Market Hall (布達佩斯中央市場)", "lat": 47.4868, "lng": 19.0586,
         "address": "Vámház krt. 1–3, 1093 Budapest",
         "note": "Stay 1 hr · upstairs lángos · paprika, foie-gras, Pick salami, Túró Rudi, Tokaji Aszú souvenirs · Kemenes Dobos torta nearby (Vámház krt. 9)",
         "food": ["Lángos upstairs", "Paprika gift packs", "Túró Rudi", "Pick salami", "Tokaji Aszú wine"]},
        {"time_label": "17:05", "name": "Chain Bridge (Széchenyi Lánchíd 塞切尼鏈橋)", "lat": 47.4990, "lng": 19.0440,
         "address": "Széchenyi Lánchíd, Budapest",
         "note": "Stay 1 hr · iconic crossing · Danube night cruise option (~€15–18) via hajóznijó / viator"},
        {"time_label": "18:10", "name": "Lánchíd Söröző (dinner)", "lat": 47.4983, "lng": 19.0398,
         "address": "Fő u. 4, 1011 Budapest",
         "note": "Stay 1 hr · Buda-side beer-hall classic right by Chain Bridge",
         "food": ["Goulash", "Pörkölt"]},
    ]},

    {"n": 6, "date_label": "Sat 23 May",
     "theme": "Library + Synagogue + NY Café + Heroes Sq + Zoo + Opera",
     "mode": "Transit + walking", "stops": [
        {"time_label": "08:00", "name": "Metropolitan Ervin Szabó Library", "lat": 47.4904, "lng": 19.0651,
         "address": "Reviczky u. 1, 1088 Budapest", "note": "Stay 1 hr · golden Wenckheim reading room"},
        {"time_label": "09:11", "name": "Dohány Street Synagogue", "lat": 47.4955, "lng": 19.0610,
         "address": "Dohány u. 2, 1074 Budapest", "note": "Stay 1 hr · largest synagogue in Europe"},
        {"time_label": "10:18", "name": "New York Café", "lat": 47.4969, "lng": 19.0726,
         "address": "Erzsébet krt. 9–11, 1073 Budapest",
         "note": "Stay 1 hr · expect queue · 'world's most beautiful café' · Hamdi Cukrászda Dobos torta nearby"},
        {"time_label": "11:39", "name": "Heroes' Square (英雄廣場)", "lat": 47.5149, "lng": 19.0779,
         "address": "Hősök tere, 1146 Budapest",
         "note": "Stay 1 hr · Millennium Monument · Gundel Étterem nearby for heritage goulash ~3,600 HUF"},
        {"time_label": "12:49", "name": "Budapest Zoo & Botanical Garden", "lat": 47.5183, "lng": 19.0736,
         "address": "Állatkerti krt. 6–12, 1146 Budapest",
         "note": "Stay 1 hr · Art Nouveau pavilions · Széchenyi Thermal Bath next door (~13,200 HUF) if you want to swap in a soak"},
        {"time_label": "18:00", "name": "Hungarian State Opera", "lat": 47.5022, "lng": 19.0586,
         "address": "Andrássy út 22, 1061 Budapest", "note": "Stay 1 hr · evening show — tickets booked"},
    ]},

    {"n": 7, "date_label": "Sun 24 May",
     "theme": "Buda Castle Hill + Gellért + Szimpla", "mode": "Walking + bath", "stops": [
        {"time_label": "08:00", "name": "Fisherman's Bastion (漁人堡)", "lat": 47.5020, "lng": 19.0344,
         "address": "Szentháromság tér, 1014 Budapest", "note": "Stay 1 hr · arrive before 09:00 for free terrace"},
        {"time_label": "09:02", "name": "Matthias Church (馬加什教堂)", "lat": 47.5020, "lng": 19.0339,
         "address": "Szentháromság tér 2, 1014 Budapest",
         "note": "Stay 1 hr · diamond-tile roof · Ruszwurm Cukrászda Dobos torta nearby (Szentháromság u. 7)"},
        {"time_label": "10:06", "name": "Labyrinth (Buda Castle)", "lat": 47.5008, "lng": 19.0335,
         "address": "Úri u. 9, 1014 Budapest", "note": "Stay 1 hr · cave network · constant 14°C"},
        {"time_label": "11:25", "name": "Hungarian National Gallery", "lat": 47.4969, "lng": 19.0395,
         "address": "Szent György tér 2, 1014 Budapest", "note": "Stay 1 hr · in Buda Castle wing"},
        {"time_label": "12:25", "name": "Buda Castle (布達城堡)", "lat": 47.4962, "lng": 19.0395,
         "address": "Szent György tér 2, 1014 Budapest",
         "note": "Stay 1 hr · grounds + courtyards · Stand25 Michelin Bib Gourmand goulash 5 min away (Attila út 10, ~6,500 HUF, book ahead)"},
        {"time_label": "13:52", "name": "Gellért Hill (蓋勒特山)", "lat": 47.4869, "lng": 19.0460,
         "address": "Citadella sétány, 1118 Budapest",
         "note": "Stay 1 hr · Liberty Statue panorama · skip the climb by taking bus 27 from Móricz Zsigmond körtér to Búsuló Juhász stop",
         "transit": "Bus 27 Móricz Zsigmond körtér → Búsuló Juhász (skip uphill walk)",
         "washroom": "Green hut by castle gate 250 HUF · North-entrance machine reads 100 HUF (free during initial reopening)"},
        {"time_label": "15:35", "name": "Palatinus Strand Baths", "lat": 47.5325, "lng": 19.0455,
         "address": "Margitsziget, 1138 Budapest",
         "note": "Stay 1 hr · Margaret Island thermal · 3,600 HUF · bring suit + cap (spasbudapest.com)"},
        {"time_label": "17:03", "name": "Szimpla Kert (ruin bar)", "lat": 47.4975, "lng": 19.0628,
         "address": "Kazinczy u. 14, 1075 Budapest",
         "note": "Stay 1 hr · most iconic ruin pub · Karaván food court next door · Gettó Gulyás (Wesselényi u. 18) for traditional goulash + pörkölt"},
    ]},

    {"n": 8, "date_label": "Mon 25 May",
     "theme": "Danube Bend · Esztergom → Visegrád → Szentendre",
     "mode": "Driving / HÉV", "stops": [
        {"time_label": "08:00", "name": "Esztergom Basilica (埃斯泰爾戈姆聖殿)", "lat": 47.7967, "lng": 18.7355,
         "address": "Szent István tér 1, 2500 Esztergom",
         "note": "Stay 1 hr · largest church in Hungary · free parking to the right of main entrance · dome panorama"},
        {"time_label": "11:17", "name": "Visegrád Castle - Citadel", "lat": 47.7826, "lng": 18.9740,
         "address": "Várhegy, 2025 Visegrád",
         "note": "Stay 1 hr · ~137 min east · Danube-bend lookout · free WC inside castle · royal palace at base can be skipped if short on time",
         "washroom": "Free inside the castle"},
        {"time_label": "13:30", "name": "Renaissance Restaurant (Visegrád)", "lat": 47.7849, "lng": 18.9748,
         "address": "Fő u. 11, 2025 Visegrád",
         "note": "Stay 1 hr · medieval-themed lunch · costumes available for guests to cosplay"},
        {"time_label": "15:17", "name": "Szentendre Main Square (Fő tér)", "lat": 47.6677, "lng": 19.0757,
         "address": "Fő tér, 2000 Szentendre",
         "note": "Stay 1 hr · Serbian-flavoured old town · cars can't cross town centre — if north lot is full, drive around exterior to the south · take HÉV H5 back to BP (city pass + extension ticket; alight Batthyány tér)",
         "transit": "Return: HÉV H5 with extension ticket to Batthyány tér",
         "washroom": "North-side and south-side public washrooms in town"},
    ]},

    {"n": 9, "date_label": "Tue 26 May",
     "theme": "Free day · Retek dinner", "mode": "Flex", "stops": [
        {"time_label": "10:00", "name": "Free morning · pick from Széchenyi Bath / Margaret Island bike / Andrássy walk / House of Terror / Lake Balaton day-trip",
         "lat": 47.4990, "lng": 19.0570, "address": "Budapest",
         "note": "ChicTrip leaves this day blank (還沒有排這天的行程呦). Add a stop here if you commit to one."},
        {"time_label": "18:00", "name": "Retek Bistro (dinner)", "lat": 47.5080, "lng": 19.0250,
         "address": "Retek u., 1024 Budapest",
         "note": "Stay 2 hr · 18:00 reservation · goulash + Hungarian mains · +36 20 253 5596 · retekbisztro.hu",
         "food": ["Goulash (Halászlé fish soup if available)", "Paprikás Csirke", "Almás Pite"]},
    ]},

    {"n": 10, "date_label": "Wed 27 May",
     "theme": "Departure → Liszt Ferenc Airport", "mode": "Transit", "stops": [
        {"time_label": "03:00", "name": "Extremly Central - Balcony (check-out)", "lat": 47.4990, "lng": 19.0570,
         "address": "Budapest", "note": "Leave 03:00 · pre-book taxi or 100E airport bus"},
        {"time_label": "03:37", "name": "Liszt Ferenc Airport Terminal 2", "lat": 47.4329, "lng": 19.2613,
         "address": "BUD Airport, 1185 Budapest",
         "note": "Stay 1 hr · 37 min transit · check-in 3 hr prior"},
    ]},
]


# Trip is in the future — no check-ins, photos, voice notes yet.
CHECK_INS: dict[int, list[int]] = {}
PHOTOS: dict[tuple[int, int], list[str]] = {}
VOICE_NOTES: dict[tuple[int, int], str] = {}

# Reuse the curated Budapest street-food picks (relevant for days 5–10).
STREET_FOOD = bp.STREET_FOOD
