"""Vienna + Budapest 10-day trip — copied from ChicTrip planner (chictrip.com.tw)."""
from datetime import date

from . import budapest as bp


TRIP = {
    "name": "Vienna + Budapest · 10 Days · Spring 2026",
    "destination": "Vienna, Austria + Budapest, Hungary",
    "start_date": date(2026, 5, 17),
    "end_date": date(2026, 5, 27),
    "season": "Late spring (15–24 °C)",
    "style": "Imperial cities · castles · Danube",
    "pace": "Packed",
    "source_url": "https://www.chictrip.com.tw/explore",
    "hotel_name": "arte Hotel Wien Stadthalle (Days 1–4) · Extremly Central Balcony, Budapest (Days 5–10)",
    "hotel_lat": 48.1985,
    "hotel_lng": 16.3357,
    "hotel_address": "Mariahilfer Str., 1150 Wien (Vienna leg)",
    "journal": "",
}

BOOKINGS = [
    {"label": "Vancouver YVR → Vienna VIE flight — Sun May 17", "url": "", "done": False},
    {"label": "Schönbrunn Palace tour — Day 2 (NT$2,185)", "url": "https://www.schoenbrunn.at/", "done": False},
    {"label": "Vienna Fiaker carriage tour — Day 1 (NT$1,204)", "url": "https://www.fiaker.at/", "done": False},
    {"label": "Kunsthistorisches Museum ticket — Day 1 (NT$812)", "url": "https://www.khm.at/", "done": False},
    {"label": "Vienna → Budapest train (ÖBB Railjet)", "url": "https://www.oebb.at/", "done": False},
    {"label": "Hungarian State Opera — Sat May 23 evening", "url": "https://www.opera.hu/", "done": False},
    {"label": "Europe eSIM (NT$69)", "url": "https://www.chictrip.com.tw/", "done": False},
    {"label": "Budapest BUD departure flight — Wed May 27, 03:37", "url": "", "done": False},
]

COMPANION_DOCS = [
    {"name": "🇦🇹 ChicTrip source plan", "file_path": "https://www.chictrip.com.tw/explore"},
    {"name": "🍲 Budapest food guide", "file_path": "/static/Budapest_5_Day/food.md"},
    {"name": "🗣 Phrasebook (DE/HU)", "file_path": "/static/Budapest_5_Day/phrasebook.md"},
    {"name": "🚻 Washroom finder", "file_path": "/static/Budapest_5_Day/washrooms.md"},
]

ROUTES = [
    {"day_n": 1, "label": "Day 1 · Vienna icons (Stephansdom + Hofburg)", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Vienna+Airport/arte+Hotel+Wien+Stadthalle/Stephansdom/Hofburg+Wien/Kunsthistorisches+Museum/?travelmode=transit"},
    {"day_n": 2, "label": "Day 2 · Schönbrunn + Naschmarkt + Opera", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/arte+Hotel+Wien+Stadthalle/Sch%C3%B6nbrunn+Palace/Naschmarkt/Karlskirche/Vienna+State+Opera/?travelmode=transit"},
    {"day_n": 3, "label": "Day 3 · Hundertwasser + Kinsky + Franzensburg", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/arte+Hotel+Wien+Stadthalle/Justizpalast+Wien/Hundertwasserhaus/Palais+Kinsky/Franzensburg+Laxenburg/?travelmode=transit"},
    {"day_n": 4, "label": "Day 4 · Wachau Valley loop", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Klosterneuburg+Monastery/Krems+an+der+Donau/D%C3%BCrnstein/Aggstein+Castle/Melk+Abbey/St.+P%C3%B6lten/?travelmode=driving"},
    {"day_n": 5, "label": "Day 5 · Budapest icons (Market → Parliament)", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Great+Market+Hall+Budapest/Shoes+on+the+Danube/Chain+Bridge+Budapest/St.+Stephen's+Basilica+Budapest/Hungarian+Parliament/?travelmode=walking"},
    {"day_n": 6, "label": "Day 6 · Synagogue → Heroes Sq → Opera", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Ervin+Szab%C3%B3+Library/Doh%C3%A1ny+Street+Synagogue/New+York+Caf%C3%A9/Heroes+Square+Budapest/Budapest+Zoo/Hungarian+State+Opera/?travelmode=transit"},
    {"day_n": 7, "label": "Day 7 · Buda Castle + Gellért + Szimpla", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Fisherman's+Bastion/Matthias+Church+Budapest/Buda+Castle/Gell%C3%A9rt+Hill/Palatinus+Strand+Baths/Szimpla+Kert/?travelmode=transit"},
    {"day_n": 8, "label": "Day 8 · Danube Bend (Esztergom → Szentendre)", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Esztergom+Basilica/Visegr%C3%A1d+Castle/Szentendre/?travelmode=driving"},
    {"day_n": 9, "label": "Day 9 · Budapest free day (TBD)", "pdf_path": "", "map_url": ""},
    {"day_n": 10, "label": "Day 10 · Departure → Liszt Ferenc Airport", "pdf_path": "",
     "map_url": "https://www.google.com/maps/dir/Extremly+Central+Balcony+Budapest/Liszt+Ferenc+Airport+Terminal+2/?travelmode=transit"},
]


DAYS = [
    {"n": 1, "date_label": "Mon 18 May",
     "theme": "Vienna arrival → Stephansdom + Hofburg loop", "mode": "Walking", "stops": [
        {"time_label": "09:00", "name": "Vienna Airport (VIE)", "lat": 48.1102, "lng": 16.5697,
         "address": "1300 Schwechat, Austria", "note": "Pass through · CAT/S7 train to city ~30 min"},
        {"time_label": "10:00", "name": "arte Hotel Wien Stadthalle (check-in)", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Drop bags · 20 min stay"},
        {"time_label": "10:49", "name": "Fenster Café", "lat": 48.2117, "lng": 16.3735,
         "address": "Griechengasse 10, 1010 Wien", "note": "Stay 1 hr · brunch"},
        {"time_label": "11:54", "name": "Ankeruhr (Anker Clock 安可鐘)", "lat": 48.2110, "lng": 16.3741,
         "address": "Hoher Markt 10–11, 1010 Wien", "note": "Stay 1 hr · figures parade at noon"},
        {"time_label": "13:00", "name": "Mozarthaus Vienna (莫扎特之家)", "lat": 48.2087, "lng": 16.3727,
         "address": "Domgasse 5, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "14:04", "name": "St. Stephen's Cathedral (Stephansdom)", "lat": 48.2084, "lng": 16.3725,
         "address": "Stephansplatz 3, 1010 Wien", "note": "Stay 1 hr · climb south tower (343 steps)"},
        {"time_label": "15:09", "name": "Plague Column (Pestsäule)", "lat": 48.2088, "lng": 16.3700,
         "address": "Graben, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "16:11", "name": "Peterskirche (St Peter's)", "lat": 48.2096, "lng": 16.3697,
         "address": "Petersplatz, 1010 Wien", "note": "Stay 1 hr · free organ recitals 15:00"},
        {"time_label": "17:15", "name": "Café Demel", "lat": 48.2087, "lng": 16.3667,
         "address": "Kohlmarkt 14, 1010 Wien", "note": "Stay 1 hr · imperial Sachertorte"},
        {"time_label": "18:20", "name": "Austrian National Library (Prunksaal)", "lat": 48.2068, "lng": 16.3661,
         "address": "Josefsplatz 1, 1010 Wien", "note": "Stay 1 hr · closes 18:00, reschedule earlier"},
        {"time_label": "19:23", "name": "Augustinerkirche", "lat": 48.2058, "lng": 16.3669,
         "address": "Augustinerstraße 3, 1010 Wien", "note": "Stay 1 hr · Habsburg hearts crypt"},
        {"time_label": "20:32", "name": "Heldenplatz", "lat": 48.2065, "lng": 16.3635,
         "address": "Heldenplatz, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "21:35", "name": "Hofburg Palace", "lat": 48.2069, "lng": 16.3650,
         "address": "Michaelerkuppel, 1010 Wien", "note": "Stay 1 hr · Fiaker carriage tour deal NT$1,204"},
        {"time_label": "22:42", "name": "Kunsthistorisches Museum", "lat": 48.2038, "lng": 16.3614,
         "address": "Maria-Theresien-Platz, 1010 Wien", "note": "Ticket NT$812 · closes 21:00 — move to morning"},
        {"time_label": "23:17", "name": "Mozart Monument", "lat": 48.2052, "lng": 16.3637,
         "address": "Burggarten, 1010 Wien", "note": "Stay 30 min"},
        {"time_label": "23:59", "name": "Gasthaus Rebhuhn", "lat": 48.2098, "lng": 16.3743,
         "address": "Berggasse 24, 1090 Wien", "note": "Stay 1 hr · late dinner — verify open hours"},
    ]},

    {"n": 2, "date_label": "Tue 19 May",
     "theme": "Schönbrunn → Naschmarkt → Karlskirche → Opera",
     "mode": "Transit + walking", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · breakfast"},
        {"time_label": "09:35", "name": "Schönbrunn Palace (美泉宮)", "lat": 48.1845, "lng": 16.3122,
         "address": "Schönbrunner Schloßstraße 47, 1130 Wien",
         "note": "Stay 3 hr · tour deal NT$2,185 · book Grand Tour"},
        {"time_label": "13:11", "name": "Naschmarkt", "lat": 48.1986, "lng": 16.3631,
         "address": "Naschmarkt, 1060 Wien", "note": "Stay 1 hr · open-air market"},
        {"time_label": "14:12", "name": "Georg am Naschmarkt", "lat": 48.1986, "lng": 16.3631,
         "address": "Naschmarkt 33, 1060 Wien", "note": "Stay 10 min"},
        {"time_label": "14:26", "name": "Nordsee", "lat": 48.2089, "lng": 16.3712,
         "address": "Kärntner Straße 25, 1010 Wien", "note": "Stay 1 hr · seafood chain"},
        {"time_label": "15:28", "name": "Vienna Secession", "lat": 48.2007, "lng": 16.3658,
         "address": "Friedrichstraße 12, 1010 Wien", "note": "Stay 1 hr · Klimt Beethoven Frieze"},
        {"time_label": "16:36", "name": "Wien Museum (維也納博物館)", "lat": 48.1996, "lng": 16.3712,
         "address": "Karlsplatz 8, 1040 Wien", "note": "Stay 1 hr"},
        {"time_label": "17:39", "name": "Karlskirche (卡爾教堂)", "lat": 48.1985, "lng": 16.3722,
         "address": "Karlsplatz, 1040 Wien", "note": "Stay 1 hr · panoramic dome elevator"},
        {"time_label": "18:50", "name": "Alt Wien Kaffee", "lat": 48.2080, "lng": 16.3760,
         "address": "Bäckerstraße 9, 1010 Wien", "note": "Stay 1 hr"},
        {"time_label": "19:52", "name": "Vollpension", "lat": 48.1968, "lng": 16.3720,
         "address": "Schleifmühlgasse 16, 1040 Wien", "note": "Stay 1 hr · grandmas' cake café"},
        {"time_label": "21:04", "name": "Vienna State Opera", "lat": 48.2025, "lng": 16.3691,
         "address": "Opernring 2, 1010 Wien", "note": "Stay 1 hr · standing-room tickets €4–€10 same-day"},
        {"time_label": "22:14", "name": "Austrian Parliament", "lat": 48.2080, "lng": 16.3585,
         "address": "Dr.-Karl-Renner-Ring 3, 1017 Wien", "note": "Stay 1 hr · evening lit façade"},
        {"time_label": "23:32", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · return"},
    ]},

    {"n": 3, "date_label": "Wed 20 May",
     "theme": "Hundertwasser + Kinsky + Franzensburg (Laxenburg)",
     "mode": "Transit + driving", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr"},
        {"time_label": "09:14", "name": "Vienna Palace of Justice (Justizpalast)", "lat": 48.2090, "lng": 16.3568,
         "address": "Schmerlingplatz 11, 1010 Wien", "note": "Stay 1 hr · 5-floor atrium with caryatids"},
        {"time_label": "10:36", "name": "Hundertwasserhaus (百水公寓)", "lat": 48.2076, "lng": 16.3940,
         "address": "Kegelgasse 36–38, 1030 Wien", "note": "Stay 1 hr · only photo from outside"},
        {"time_label": "11:38", "name": "KunstHausWien (百水藝術村)", "lat": 48.2110, "lng": 16.3914,
         "address": "Untere Weißgerberstraße 13, 1030 Wien", "note": "Stay 1 hr · Hundertwasser museum"},
        {"time_label": "13:00", "name": "Palais Kinsky (金斯基宮)", "lat": 48.2110, "lng": 16.3667,
         "address": "Freyung 4, 1010 Wien", "note": "Stay 1 hr · baroque palace courtyard"},
        {"time_label": "15:31", "name": "Franzensburg (Laxenburg)", "lat": 48.0648, "lng": 16.3589,
         "address": "Schlossplatz 1, 2361 Laxenburg",
         "note": "Stay 1 hr · 91 min south by car/transit · island castle"},
        {"time_label": "17:46", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · return"},
    ]},

    {"n": 4, "date_label": "Thu 21 May",
     "theme": "Wachau Valley · Klosterneuburg → Krems → Dürnstein → Aggstein → Melk",
     "mode": "Driving (rental or guided)", "stops": [
        {"time_label": "08:00", "name": "arte Hotel Wien Stadthalle", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · early start, pack lunch"},
        {"time_label": "09:24", "name": "Klosterneuburg Monastery", "lat": 48.3060, "lng": 16.3257,
         "address": "Stiftspl. 1, 3400 Klosterneuburg", "note": "Stay 1 hr · Verdun altarpiece"},
        {"time_label": "11:19", "name": "Krems an der Donau", "lat": 48.4097, "lng": 15.6160,
         "address": "Krems an der Donau", "note": "Stay 1 hr · UNESCO old town entrance"},
        {"time_label": "12:32", "name": "Dürnstein Parkplatz P3", "lat": 48.3979, "lng": 15.5180,
         "address": "Dürnstein", "note": "Stay 1 hr · blue church + Richard the Lionheart castle"},
        {"time_label": "19:55", "name": "Aggstein Castle (阿格斯泰因城堡)", "lat": 48.3093, "lng": 15.4248,
         "address": "Aggstein 5, 3642 Aggsbach", "note": "Stay 1 hr · ruined Danube cliff castle"},
        {"time_label": "21:57", "name": "Melk Abbey (梅爾克修道院)", "lat": 48.2280, "lng": 15.3340,
         "address": "Abt-Berthold-Dietmayr-Straße 1, 3390 Melk",
         "note": "Stay 1 hr · closes 17:30 — re-time to afternoon"},
        {"time_label": "23:23", "name": "St. Pölten Tourismus", "lat": 48.2058, "lng": 15.6232,
         "address": "Rathauspl. 1, 3100 St. Pölten", "note": "Stay 1 hr"},
        {"time_label": "01:17 +1", "name": "arte Hotel Wien Stadthalle (late return)", "lat": 48.1985, "lng": 16.3357,
         "address": "Mariahilfer Str., 1150 Wien", "note": "Stay 1 hr · consider overnighting in Melk instead"},
    ]},

    {"n": 5, "date_label": "Fri 22 May",
     "theme": "Budapest icons · Market → Shoes → Chain Bridge → Basilica → Parliament",
     "mode": "Walking", "stops": [
        {"time_label": "08:00", "name": "Extremly Central - Balcony (BP hotel check-in)", "lat": 47.4990, "lng": 19.0570,
         "address": "Budapest", "note": "Stay 30 min · drop bags after Vienna→Budapest train"},
        {"time_label": "08:39", "name": "Belvárosi Disznótoros - Károlyi utca", "lat": 47.4912, "lng": 19.0581,
         "address": "Károlyi u., 1053 Budapest", "note": "Stay 1 hr · butcher counter — point at sausage"},
        {"time_label": "09:48", "name": "Great Market Hall (布達佩斯中央市場)", "lat": 47.4868, "lng": 19.0586,
         "address": "Vámház krt. 1–3, 1093 Budapest",
         "note": "Stay 1 hr · upstairs lángos, paprika souvenir"},
        {"time_label": "11:04", "name": "Shoes on the Danube Bank", "lat": 47.5039, "lng": 19.0454,
         "address": "Id. Antall József rkp., 1054 Budapest",
         "note": "Stay 1 hr · WWII memorial · 60 cast-iron pairs"},
        {"time_label": "12:15", "name": "Chain Bridge (Széchenyi Lánchíd 塞切尼鏈橋)", "lat": 47.4990, "lng": 19.0440,
         "address": "Széchenyi Lánchíd, Budapest", "note": "Stay 1 hr · iconic crossing"},
        {"time_label": "13:28", "name": "St. Stephen's Basilica", "lat": 47.5009, "lng": 19.0537,
         "address": "Szent István tér 1, 1051 Budapest", "note": "Stay 1 hr · climb dome 364 steps"},
        {"time_label": "14:42", "name": "Hungarian Parliament", "lat": 47.5072, "lng": 19.0457,
         "address": "Kossuth Lajos tér 1–3, 1055 Budapest", "note": "Stay 1 hr · book English tour ahead"},
        {"time_label": "15:56", "name": "Retek Mini", "lat": 47.5080, "lng": 19.0250,
         "address": "Retek u., 1024 Budapest", "note": "Stay 1 hr · Buda side bistro"},
    ]},

    {"n": 6, "date_label": "Sat 23 May",
     "theme": "Library + Synagogue + NY Café + Heroes Sq + Zoo + Opera",
     "mode": "Transit + walking", "stops": [
        {"time_label": "08:00", "name": "Metropolitan Ervin Szabó Library", "lat": 47.4904, "lng": 19.0651,
         "address": "Reviczky u. 1, 1088 Budapest", "note": "Stay 1 hr · golden Wenckheim reading room"},
        {"time_label": "09:11", "name": "Dohány Street Synagogue", "lat": 47.4955, "lng": 19.0610,
         "address": "Dohány u. 2, 1074 Budapest", "note": "Stay 1 hr · largest synagogue in Europe"},
        {"time_label": "10:18", "name": "New York Café", "lat": 47.4969, "lng": 19.0726,
         "address": "Erzsébet krt. 9–11, 1073 Budapest",
         "note": "Stay 1 hr · expect queue · 'world's most beautiful café'"},
        {"time_label": "11:39", "name": "Heroes' Square (英雄廣場)", "lat": 47.5149, "lng": 19.0779,
         "address": "Hősök tere, 1146 Budapest", "note": "Stay 1 hr · Millennium Monument"},
        {"time_label": "12:49", "name": "Budapest Zoo & Botanical Garden", "lat": 47.5183, "lng": 19.0736,
         "address": "Állatkerti krt. 6–12, 1146 Budapest", "note": "Stay 1 hr · Art Nouveau pavilions"},
        {"time_label": "18:00", "name": "Hungarian State Opera", "lat": 47.5022, "lng": 19.0586,
         "address": "Andrássy út 22, 1061 Budapest", "note": "Stay 1 hr · catch evening show — book tickets"},
    ]},

    {"n": 7, "date_label": "Sun 24 May",
     "theme": "Buda Castle Hill + Gellért + Szimpla", "mode": "Walking + bath", "stops": [
        {"time_label": "08:00", "name": "Fisherman's Bastion (漁人堡)", "lat": 47.5020, "lng": 19.0344,
         "address": "Szentháromság tér, 1014 Budapest", "note": "Stay 1 hr · arrive before 09:00 for free terrace"},
        {"time_label": "09:02", "name": "Matthias Church (馬加什教堂)", "lat": 47.5020, "lng": 19.0339,
         "address": "Szentháromság tér 2, 1014 Budapest", "note": "Stay 1 hr · diamond-tile roof"},
        {"time_label": "10:06", "name": "Labyrinth (Buda Castle)", "lat": 47.5008, "lng": 19.0335,
         "address": "Úri u. 9, 1014 Budapest", "note": "Stay 1 hr · cave network · constant 14°C"},
        {"time_label": "11:25", "name": "Hungarian National Gallery", "lat": 47.4969, "lng": 19.0395,
         "address": "Szent György tér 2, 1014 Budapest", "note": "Stay 1 hr · in Buda Castle wing"},
        {"time_label": "12:25", "name": "Buda Castle (布達城堡)", "lat": 47.4962, "lng": 19.0395,
         "address": "Szent György tér 2, 1014 Budapest", "note": "Stay 1 hr · grounds + courtyards"},
        {"time_label": "13:52", "name": "Gellért Hill (蓋勒特山)", "lat": 47.4869, "lng": 19.0460,
         "address": "Citadella sétány, 1118 Budapest", "note": "Stay 1 hr · Liberty Statue panorama"},
        {"time_label": "15:35", "name": "Palatinus Strand Baths", "lat": 47.5325, "lng": 19.0455,
         "address": "Margitsziget, 1138 Budapest", "note": "Stay 1 hr · island thermal — bring suit/cap"},
        {"time_label": "17:03", "name": "Szimpla Kert (ruin bar)", "lat": 47.4975, "lng": 19.0628,
         "address": "Kazinczy u. 14, 1075 Budapest",
         "note": "Stay 1 hr · iconic ruin pub · Karaván food court next door"},
    ]},

    {"n": 8, "date_label": "Mon 25 May",
     "theme": "Danube Bend · Esztergom → Visegrád → Szentendre",
     "mode": "Driving / HÉV", "stops": [
        {"time_label": "08:00", "name": "Esztergom Basilica (埃斯泰爾戈姆聖殿)", "lat": 47.7967, "lng": 18.7355,
         "address": "Szent István tér 1, 2500 Esztergom",
         "note": "Stay 1 hr · largest church in Hungary · dome views"},
        {"time_label": "11:17", "name": "Visegrád Castle - Citadel", "lat": 47.7826, "lng": 18.9740,
         "address": "Várhegy, 2025 Visegrád",
         "note": "Stay 1 hr · 137 min transit east · Danube bend lookout"},
        {"time_label": "13:30", "name": "Renaissance Restaurant (Visegrád)", "lat": 47.7849, "lng": 18.9748,
         "address": "Fő u. 11, 2025 Visegrád", "note": "Stay 1 hr · medieval-themed lunch"},
        {"time_label": "15:17", "name": "Szentendre Main Square (Fő tér)", "lat": 47.6677, "lng": 19.0757,
         "address": "Fő tér, 2000 Szentendre",
         "note": "Stay 1 hr · Serbian-flavored old town · take HÉV H5 back to BP"},
    ]},

    {"n": 9, "date_label": "Tue 26 May",
     "theme": "Free day · not yet planned (ChicTrip empty)", "mode": "Flex", "stops": [
        {"time_label": "—", "name": "Free day · TBD", "lat": 47.4990, "lng": 19.0570,
         "address": "Budapest",
         "note": "ChicTrip note: 還沒有排這天的行程呦. Suggestions: Széchenyi Bath, Margaret Island bike, Andrássy walk, Lake Balaton day trip, House of Terror."},
    ]},

    {"n": 10, "date_label": "Wed 27 May",
     "theme": "Departure → Liszt Ferenc Airport", "mode": "Transit", "stops": [
        {"time_label": "03:00", "name": "Extremly Central - Balcony (check-out)", "lat": 47.4990, "lng": 19.0570,
         "address": "Budapest", "note": "Leave 03:00 · pre-book taxi or 100E airport bus"},
        {"time_label": "03:37", "name": "Liszt Ferenc Airport Terminal 2", "lat": 47.4329, "lng": 19.2613,
         "address": "BUD Airport, 1185 Budapest",
         "note": "Stay 1 hr · 37 min transit · check-in 3 hr prior"},
    ]},
]


# Trip is in the future — no check-ins, photos, voice notes yet.
CHECK_INS: dict[int, list[int]] = {}
PHOTOS: dict[tuple[int, int], list[str]] = {}
VOICE_NOTES: dict[tuple[int, int], str] = {}

# Reuse the curated Budapest street-food picks (relevant for days 5–10).
STREET_FOOD = bp.STREET_FOOD
